Restore disconnect-plug-host-hunspell hook and host-hunspell declaration
We need this to be able to unmount the existing mount point for the
last time, otherwise removal of the Firefox snap fails halfway through
with this error:

error: cannot perform the following tasks:
- Remove data for snap "firefox" (4111) (unlinkat /var/snap/firefox/common/host-hunspell/en_US.dic: read-only file system)