Pin Cbindgen to version 0.29.2.
0.29.4 causes

In file included from Unified_cpp_accessible_base1.cpp:20:
In file included from /build/firefox/parts/firefox/build/accessible/base/SelectionManager.cpp:10:
In file included from /build/firefox/parts/firefox/build/accessible/generic/HyperTextAccessible-inl.h:14:
In file included from /build/firefox/parts/firefox/build/layout/generic/nsFrameSelection.h:30:
In file included from /build/firefox/parts/firefox/build/obj-x86_64-pc-linux-gnu/instrumented/dist/include/nsBidiPresUtils.h:10:
In file included from /build/firefox/parts/firefox/build/obj-x86_64-pc-linux-gnu/instrumented/dist/include/gfxContext.h:11:
In file included from /build/firefox/parts/firefox/build/obj-x86_64-pc-linux-gnu/instrumented/dist/include/gfxUtils.h:24:
In file included from /build/firefox/parts/firefox/build/obj-x86_64-pc-linux-gnu/instrumented/dist/include/mozilla/webrender/WebRenderTypes.h:11:
In file included from /build/firefox/parts/firefox/build/obj-x86_64-pc-linux-gnu/instrumented/dist/include/mozilla/webrender/webrender_ffi.h:103:
/build/firefox/parts/firefox/build/obj-x86_64-pc-linux-gnu/instrumented/dist/include/mozilla/webrender/webrender_ffi_generated.h:6718:53: error: use of undeclared identifier 'COUNT'
constexpr static const BudgetType BudgetType_VALUES[COUNT] = { BudgetType::SharedColor8Linear, BudgetType::SharedColor8Nearest, BudgetType::SharedColor8Glyphs, BudgetType::SharedAlpha8, BudgetType::SharedAlpha8Glyphs, BudgetType::SharedAlpha16, BudgetType::Standalone, };