Bump rust requirement (1.64.0)
error: failed to compile `cbindgen v0.25.0`, intermediate artifacts can be found at `/tmp/cargo-installzPtKtR`

Caused by:
  package `cbindgen v0.25.0` cannot be built because it requires rustc 1.64 or newer, while the currently active rustc version is 1.63.0