Rust 1.82->1.85.
https://github.com/rust-random/getrandom/commit/59d52049773a4f974da4818cf58f96edfc9159f1
bumped the MSRV from 1.63 to 1.85, causing the build failure

--->
  Downloaded getrandom v0.4.1
error: failed to compile `cbindgen v0.29.2`, intermediate artifacts can be found at `/tmp/cargo-installiLZpaJ`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
Caused by:
  failed to parse manifest at `/builds/worker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/getrandom-0.4.1/Cargo.toml`
Caused by:
  feature `edition2024` is required
  The package requires the Cargo feature called `edition2024`, but that feature is not stabilized in this version of Cargo (1.82.0 (8f40fc59f 2024-08-21)).
  Consider trying a newer version of Cargo (this may require the nightly release).
  See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#edition-2024 for more information about the status of this feature.
<---

From https://firefoxci.taskcluster-artifacts.net/PzwkkgbTQxm1GS31LfATiA/0/public/logs/live_backing.log